apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: example-user
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
    - name: user-svc-grpc-port
      port: 8282
      targetPort: 8282
    - name: user-svc-grpc-metrics-port
      port: 8283
      targetPort: 8283

